### ISSUE TITLE
Environment creation in the backend does not return error message

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCoreBundle#1]
Try to create an environment with Capital. It should return an error indicating that the environment should be lowercase. Howerver, in a prod environment we get an error 500 without explication. The real error message is found in the logs.

![image](https://cloud.githubusercontent.com/assets/1359953/25704474/dd2a060e-30d9-11e7-81b1-9bbcea22e3ca.png)

**Comment by dameert** [comment]
![image](https://cloud.githubusercontent.com/assets/1359953/25704497/f5cb636a-30d9-11e7-9fd5-f935051976fe.png)

**Comment by dameert** [comment]
Bigger issue, the environment is created, even though only lowercase should be used.
![image](https://cloud.githubusercontent.com/assets/1359953/25704901/9e62957e-30db-11e7-9ee4-abd179517859.png)

**Comment by ems-project** [comment]
I just added a regex validation on the form. So from the following regex /^[a-z][a-z0-9\-_]*$/  has been added has constraint (commit b8c976d206e6c21e36840158209e3622a2f204e4)

<img width="388" alt="capture d ecran 2017-05-04 a 22 19 56" src="https://cloud.githubusercontent.com/assets/24774220/25723322/de045bf4-3117-11e7-8340-fc4394f6df4f.png">
