### ISSUE TITLE
One field in tab required + checkbox is causing issues

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCoreBundle#11]
My tabs have many fields in it. One is a checkbox, one is a textfield. The textfield is required.
As soon as the checkbox is ticked, all fields become required.

**Comment by ems-project** [comment]
Should be fixed by commit 54a07011c12323109e6878c5922b14f22f3ab465 (could test it core  >= 1.6.14)

**Comment by dameert** [comment]
This is indeed fixed
