### ISSUE TITLE
Migrate bower to webpack (we are unable to update ckeditor)

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCoreBundle#118]
Webpack runs partially in dev mode.
Bower is run in prod mode (but all bower config got removed).

We should migrate to webpack (and finish integration of ckeditor, and maybe others? in webpack)

**Comment by Davidmattei** [comment]
Yes and then we can also implement https://codemirror.net/ easily!

**Comment by theus77** [comment]
It's done in branch refact_js, wainting for merge
