### ISSUE TITLE
e:c:m computed fields not calculated.

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCoreBundle#13]
Computed fields are not calculated with the e:c:m command. Maybe because I can only run with the --raw option? Due to authorisation token error.

**Comment by dameert** [comment]
![image](https://user-images.githubusercontent.com/1359953/28657050-6dd74664-72a5-11e7-9a3a-bb4654a4c6cd.png)

**Comment by ems-project** [comment]
I think that this ticket has been resolved? Right?

**Comment by dameert** [comment]
Yes calculated fields are working through command line!
Op wo 2 aug. 2017 om 23:51 schreef elasticms <notifications@github.com>
