### ISSUE TITLE
Improvement: Char Filter on fields used for search

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCoreBundle#18]
Trying to implement "suggestions" in our query, I discover that the word "class" and "div" are very popular in our content. In fact, that is because it is used in every wysiwyg editor!

The tokenizer should be informed to strip html tags before indexing the content (that is only for _search):
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-htmlstrip-charfilter.html

Can this option be added? In particular usefull for "copy_to" fields.

**Comment by ems-project** [comment]
Indeed. But it's a big change we need a analyzers management tools. And what about indexing ems links in href tags if they are stripped?

**Comment by ems-project** [comment]
See core 1.6.18 and local user 1.6.5
