### ISSUE TITLE
Memory leak in FormDataCollector.php

### ISSUE THREAD

**Issue by christophe-compere** [ems-project/EMSCoreBundle#19]
When importing with the command ems:contenttype:migrate (tesos-admin project), the command stops after 20% with the allocation error message.
![image](https://user-images.githubusercontent.com/14075032/29214662-834c3fea-7ea8-11e7-856c-e553583a1364.png)
It seems that there is a memory leak in the method FormDataCollector.php. See: https://github.com/symfony/symfony/issues/21009

**Comment by ems-project** [comment]
I see where it comes, you should tried the --raw(as you don't have computed fields nor update structure

**Comment by ems-project** [comment]
I fixed some memory leaks in commit 3202b2fa446cedce4feb0f0ed8320d3b3dd31419. It shoudl works now.

Please use the "-e prod" option. Indeed by default it runs in debug mode and logs all sql queries in memory (it may looks like a memory leak)

**Comment by ems-project** [comment]
More info:
https://stackoverflow.com/questions/9699185/memory-leaks-symfony2-doctrine2-exceed-memory-limit
https://stackoverflow.com/questions/13093689/is-there-a-way-to-free-the-memory-allotted-to-a-symfony-2-form-object
