### ISSUE TITLE
Wysiwyg profile assigned on one textarea

### ISSUE THREAD

**Issue by christophe-compere** [ems-project/EMSCoreBundle#28]
In ems, there is the possibility to create wysiwyg custom profiles. And assign them to specific users.
I would like to be also able to assign it to a specific wysiwyg field.

**Comment by ems-project** [comment]
What is your business case? I agree that some WYSIWYG functionalities might be dangerous for some authors. But why do you want to strip the WYSIWYG functionalities from fields to fields. Do you expect that your authors will not verify thier works?

**Comment by christophe-compere** [comment]
In one page, the text of the wysiwyg textarea is in included in a content area with TOC based on H1 and H2.
This wysiwyg text is placed under a H2 title, so it is forbidden to put H1 and H2 content in this specific wysiwyg. I have to remove H1 and H2 in the "format" dropdown of this specific wysiwyg.

**Comment by theus77** [comment]
A new version 1.6.75 has been released Today with those options
