### ISSUE TITLE
ContainerFieldType class is ignored when in TabsFieldType

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCoreBundle#3]
> TabsFieldType
>> ContainerFieldType "Français"
>> ContainerFieldType "Nederlands"
>> ContainerFieldType "Deutch"
>> ContainerFieldType "English"
>> ContainerFieldType "Import Information" bootstrap-class  = pull-right

The desired effect:
![image](https://cloud.githubusercontent.com/assets/1359953/25738514/eaf7d37a-317d-11e7-9a8a-7ee5e485edd8.png)

But the class "pull-right" is ignored in this configuration.

**Comment by ems-project** [comment]
Indeep that field was not used inside a tab. It's a cool way to use the value in that case. Thanks for the change request. Caution: this bootstrap-class is considered only if it isn't exactly equal to col-md-12 (default value). Commit 14612ad7d77c5f58b8cac8722a23c6618542befc
