### ISSUE TITLE
Unpublish button not available

### ISSUE THREAD

**Issue by christophe-compere** [ems-project/EMSCoreBundle#31]
For the publisher, the "Unpublish from" button is not available when a revision is published in some environment.
In https://github.com/ems-project/EMSCoreBundle/blob/master/Resources/views/elements/revision-toolbar.html.twig , line 136 should be 

{% if (is_granted('ROLE_WEBMASTER') or is_granted(instance.contentType.publishRole)) and ((environments|length > 0 and not current) or (environments|length > 1 and current)) %}

in stead of 

{% if is_granted('ROLE_WEBMASTER') and is_granted(instance.contentType.publishRole) and ((environments|length > 0 and not current) or (environments|length > 1 and current)) %}

**Comment by ems-project** [comment]
It has been fixed. Everything is now based on the content type's publish role
