### ISSUE TITLE
New command "ems:environment:list"

### ISSUE THREAD

**Issue by christophe-compere** [ems-project/EMSCoreBundle#32]
Hi,
Is it possible to create this command:

php bin/console ems:environment:list

To get the list of all environment names available.
Because the admin might be down ( something like http://capacity.test.paas.socialsecurity.be/ems/environment) and if the solution is to rebuild environments (php bin/console ems:environment:rebuild), knowing their names helps.
Thanks.

**Comment by ems-project** [comment]
A command will be available from core 1.7.6
