### ISSUE TITLE
Validation on unicity of multiple keys

### ISSUE THREAD

**Issue by christophe-compere** [ems-project/EMSCoreBundle#35]
For a specific CT, when finilising a draft , the system should verify if a combination of multiple fields is unique. And if not, should refuse it and show an error.

**Comment by theus77** [comment]
You can use a computed field to generate the field. After that you can, in the post process, query elasticsearch to see if another object has the same key;

NB: the cant_be_finalized function will come with core 1.6.76

{% set result = {'type': 'my_type', 'index': 'id_preview', 'body': {
 'query' : {
     'term' : {
          'my_field': _source
}
}
} }|search %}

{% for item in result.hits.hits %}
   {% if item._id != _id %}
       {{ cant_be_finalized('My field must be unque') }}
   {% endif %}
{% endfor %}

{{ _source.asset|json_encode|raw }}
