### ISSUE TITLE
Multiple "Delete" button in the Revisions tab

### ISSUE THREAD

**Issue by christophe-compere** [ems-project/EMSCoreBundle#37]
Hi,
In a page of revision of a specific CT, below, in the "Revisions" tab (see screenshot), customers found not intuitive to see on each line a "Delete" button that do the same thing : delete all revisions in one action.
They thought that the "Delete" button was made to delete the specific revision. And they expected to find a "Delete all" button above or below the list to delete all revisions in one action.
And beter: a new column with a check button, like that, the user can select which revision to delete.
![image](https://user-images.githubusercontent.com/14075032/37345695-cb657bac-26cd-11e8-95fa-45cc03d6523d.png)

**Comment by theus77** [comment]
The delete button has been removed from the revision toolbar. Instead now there is a single button "Remove all revisions". Since commiy cc45f21ddbdb3d777053f1a8c2e532db980ca4a2
