### ISSUE TITLE
Error 500 on "home" for anonymous user

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCoreBundle#4]
![image](https://cloud.githubusercontent.com/assets/1359953/25797641/64c2c522-33de-11e7-967c-8384c3f24a78.png)
I think there is a general problem with error handling. Whenever an error is thrown, they are thrown as error 500 and the message (needed to solve the problem, e.g. "you should log in") is not shown to the end user.

**Comment by dameert** [comment]
It seems to be related to the cache (I was logged in before the weekend) On monday I got the error 500. Clear cache solved the issue?

**Comment by ems-project** [comment]
Was corrected by commit 945f66ac6b7ae61a2c715dd401e5ea337f4b5eb1
