### ISSUE TITLE
When LDAP takes more then 30 seconds, we should show this

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCoreBundle#568]
Because leaving it run for more then 30seconds might give 504 gateway error on cloud platforms which leave the users confused about the reason why.

WHen they see that LDAP is not working, they can still login using their regular password.

**Comment by Davidmattei** [comment]
They LDAP authentication is fully refactored in 4.0 version. 
There is a new environment variable 'EMSCO_LDAP_ENABLED' to enable LDAP authentication.

But different from before, the authentication manager will first look into the database, then use LDAP. 

https://github.com/ems-project/EMSCoreBundle/pull/1184
