### ISSUE TITLE
Recursive collectiontype

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCoreBundle#6]
I created a Content Type "menu" in order to make my menu in the backend.
However, each menu level is a collection (and can thus be nested).

But the info is not send in a nested way to elasticsearch.
The content type configuration:
[menu-test.json.txt](https://github.com/ems-project/EMSCoreBundle/files/1007229/menu-test.json.txt)

I should have (pseudo json):
```
Root: "menu name"
Level 1: [
  {Name: "Level 1.1 item",
   Level 2: [ {Name: "Level 2.1 item" } ]}

  {Name: "level 1.2 item"}
]
```

But instead I get:
```
Root: "menu name"
Level 1: [
  {Name: "Level 2.1 item",
   Level 2: [ ]}

  {Name: "level 1.2 item"}
]
```

**Comment by ems-project** [comment]
It has been fixed with the release [1.6](https://github.com/ems-project/EMSCoreBundle/releases/latest)
