### ISSUE TITLE
ems:contenttyp:migrate duplicates in default index

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCoreBundle#8]
Try running the command multiple times from another index then default.
You will see that revisions are added for your content, which is good.

But, the old revision of the content is not removed from the default index. So your page exists in the default index for each time you rebuild.

As a consequence, the page can no longer be edited by the users because there will be an error "content exists multiple time in index". Preventing the finalize operation to work correctly.

**Comment by ems-project** [comment]
Solved with commit 1942f777a4360ebff7793860537acda0a8ceb02b
